Connected to Python 3.14.7

In [ ]:
import pandas as donnesTestIa
from pandas import read_csv
donnesTestIa = read_csv("donnesTestIa.csv")

In [ ]:
read_csv("donnesTestIa.csv")

    vitesse  danger
0        45       0
1       120       1
2        60       0
3        95       1
4        75       0
5        85       1
6        50       0
7       110       1
8        72       0
9        88       1
10       40       0
11      130       1
12       65       0
13       92       1
14       55       0
15      105       1
16       78       0
17      115       1
18       48       0
19       89       1
20       70       0
21      100       1
22       52       0
23      125       1
24       68       0
25       93       1
26       80       1
27       79       0
28       90       1
29       99       1

In [ ]:
read_csv("donnesTestIa.csv")

    vitesse  danger
0        45       0
1       120       1
2        60       0
3        95       1
4        75       0
5        85       1
6        50       0
7       110       1
8        72       0
9        88       1
10       40       0
11      130       1
12       65       0
13       92       1
14       55       0
15      105       1
16       78       0
17      115       1
18       48       0
19       89       1
20       70       0
21      100       1
22       52       0
23      125       1
24       68       0
25       93       1
26       80       1
27       79       0
28       90       1
29       99       1